### ISSUE TITLE
Release initial version - Prerequisite for bundle inclusion

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_CircuitPython_USB_Host_Mass_Storage#4]
Can't install via circup currently as not present in the CircuitPython library bundle. 
Added a PR for that but failing CI as this library hasn't been released yet:
https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/455

-Edit- This library may not be fully functional yet, so maybe a version 0.1 could be released for the early adopters. It does appear to read files (smaller text files), and at the very least can be used to list the contents of a USB mass storage device successfully.

**Comment by tannewt** [comment]
Done as 0.8.0
